### ISSUE TITLE
eu-west-1 Spinnaker AMI ID does not exist

### ISSUE THREAD

**Issue by ctompkinson** [aws-quickstart/quickstart-spinnaker#4]
I receive the following error when provisioning your template

```
	SpinnakerWebServer	The image id 'ami-546f0227' does not exist
```

**Comment by kamarja** [comment]
Removed deregistered AMI's 3def2ee0a4af7eeea2c6fa2726a0c684abe47a02

**Comment by derwasp** [comment]
@kamarja it doesn't really solve the issue: it's still not possible to use this template for `eu-west-1` region. Which AMI should I use there?

**Comment by kamarja** [comment]
@derwasp we are working with Netflix to get the updated AMI's.  Please use any of the regions below. I will ping you when we have the updated AMIs in place.

      "sa-east-1": {
        "AMI": "ami-f3e1769f"
      },
      "us-east-1": {
        "AMI": "ami-4153d956"
      },
      "us-west-1": {
        "AMI": "ami-87dc9de7"
      },
      "us-west-2": {
        "AMI": "ami-21a26d41"
}

**Comment by derwasp** [comment]
Thank you @kamarja, will be waiting for an update.

**Comment by ablundgren** [comment]
Any status on the update?  How about details on how to create AMIs?
